### ISSUE TITLE
Examples does not work

### ISSUE THREAD

**Issue by matteodefelice** [lukas-rokka/camsRad#1]
Hi,
I have created an account and I tried to execute the sample commands in the GitHub homepage of the package:
```
> df <- cams_get_radition(username, lat=60, lon=15, 
                        date_begin="2016-01-01", date_end="2016-01-15")
Error in cams_get_radition(username, lat = 60, lon = 15, date_begin = "2016-01-01",  : 
  unused argument (lon = 15)
```
it seems that the argument is now `lng` instead of `lon`. I tried the right argument:
```
> df <- cams_get_radition(username, lat=60, lng =15, 
                        date_begin="2016-01-01", date_end="2016-01-15")
Error in match.arg(encode) : 
  'arg' should be one of “multipart”, “form”, “json”
```
the problem comes from `cams_api` but I don't have the time to debug more deeply.

**Comment by lukas-rokka** [comment]
Thank you for feedback, @matteodefelice. 

1. Documentation now updated. lon -> lng 

2. `cams_api` is POSTing a string with xml/text content, but seems like the "multipart" options work just as well as "raw".  So should now work with older httr as well.

**Comment by matteodefelice** [comment]
thank you for the update, unfortunately I still get the last error...

**Comment by lukas-rokka** [comment]
What version of xml2 do you have?

**Comment by matteodefelice** [comment]
0.1.2

**Comment by lukas-rokka** [comment]
Ok, thanks. That could be it. CRAN version of xml2 is at 1.0.0. 

I've now updated it with conservative dependency settings in the DESCRIPTION file. So if you reinstall it should updated those as well. 

It works on Travis-CI (Linux) and on my computer with windows/rstudio with latest CRAN updates (also with httr as github dev version). 

If you still get errors, could you please run it with `verbose=TRUE` in the call to `cams_api/cams_get_radiation` and paste the output here or email it to me. 

FYI: the package is also under review to [onboard to rOpenSci](https://github.com/ropensci/onboarding/issues/72).

**Comment by matteodefelice** [comment]
Now it works smoothly, it is very useful.
